### ISSUE TITLE
[BUG] - Exception pendant l'export vers home hassistant / MQTT d'un pdl production seulement

### ISSUE THREAD

**Issue by ioull** [MyElectricalData/myelectricaldata#344]
**Description du bug**
Lors de l'exportation vers homeassistant/MQTT, j'ai l'exception suivante :
```
2023-04-18 08:26:49.846 -     INFO :  current_year_last_year
2023-04-18 08:26:49.850 -     INFO :   => 0
2023-04-18 08:26:49.850 -     INFO :   => 0
Traceback (most recent call last):
  File "/app/models/jobs.py", line 207, in job_import_data
    HomeAssistant(self.usage_point_id).export()
  File "/app/models/export_home_assistant.py", line 92, in export
    self.myelectricaldata_usage_point_id("production")
  File "/app/models/export_home_assistant.py", line 555, in myelectricaldata_usage_point_id
    (stats.max_power_time(0)["value"]).strftime(self.date_format_detail),
2023-04-18 08:26:50.051 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
2023-04-18 08:26:50.051 -    ERROR :
2023-04-18 08:26:50.051 -    ERROR :  Erreur lors de l'exportation des données dans Home Assistant
2023-04-18 08:26:50.051 -    ERROR :  'str' object has no attribute 'strftime'
2023-04-18 08:26:50.052 -    ERROR :
2023-04-18 08:26:50.052 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
AttributeError: 'str' object has no attribute 'strftime'
2023-04-18 08:26:50.052 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
Ca empèche d'importer les données. Je n'aais pas cette exception en 0.8.13

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
  'XXXXXXXXXXXXXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'false'
    consumption_detail: 'false'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'false'
    consumption_price_base: '1'
    consumption_price_hc: '2'
    consumption_price_hp: '3'
    enable: 'true'
    name: Production
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_detail_max_date: '2022-08-18'
    production_max_date: '2022-08-18'
    production_max_power: 'false'
    production_price: '0.60275'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX=


```
</details>

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version : 0.8.16**

**Comment by larod241** [comment]
Je rencontre également le même problème.

**Comment by candelwick** [comment]
Idem tout était nickel en 0.8.13 :(

**Comment by m4dm4rtig4n** [comment]
Hello, j'ai reussi à reproduire le soucis avec tes datas.
Le fix sortira avec la 0.9.0.

**Comment by ioull** [comment]
Top ! Merci !!!

**Comment by candelwick** [comment]
SUPER !

**Comment by m4dm4rtig4n** [comment]
Arrivée de la 0.9.0 qui devrait fix le soucis d'ici quelques minutes.

**Comment by ioull** [comment]
Parfait ! Je n'ai plus l'exception !
