### ISSUE TITLE
[BUG] - Params wipe_influxdb et wipe_cache mis à true -> plantage sur le wipe_influxdb

### ISSUE THREAD

**Issue by alainvdu69** [MyElectricalData/myelectricaldata#368]
**Description du bug**
Params wipe_influxdb et wipe_cache mis à true -> plantage sur le wipe_influxdb
Tout se passe bien en le remettant à False
J'ai voulu effacer la totalité afin de coller aux années complètes de données dispo via l'usage des param max_date

2023-04-24 20:06:04.550 -  WARNING :  Wipe influxdb database 11.6.168.112:8086
Traceback (most recent call last):
  File "/app/main.py", line 103, in <module>
    INFLUXDB.purge_influxdb()
  File "/app/models/influxdb.py", line 133, in purge_influxdb
    self.delete_api.delete(start, stop, f'_measurement="{mesure}"', self.bucket,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/delete_api.py", line 35, in delete
    return self._service.post_delete(delete_predicate_request=predicate_request, bucket=bucket, org=org_param)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/delete_service.py", line 56, in post_delete
    (data) = self.post_delete_with_http_info(delete_predicate_request, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/delete_service.py", line 82, in post_delete_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 261, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Mon, 24 Apr 2023 18:06:04 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found

<details>
<summary>Configuration (config.yaml)</summary>

cycle: 7200  # 2H
debug: false
wipe_influxdb: true
wipe_cache: true
####################
####################
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
  card_myenedis: true

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [ ] Docker
- [ X ] HassIO

**Version : 0.8.16**

**Comment by m4dm4rtig4n** [comment]
Tu est sur quelle version d'influxdb ?

**Comment by alainvdu69** [comment]
v4.6.0

**Comment by m4dm4rtig4n** [comment]
v4.6.0 c'est la version du conteneur sur Home Assistant ?
InfluxDB est max en V2.X.X :)

**Comment by m4dm4rtig4n** [comment]
Bon j'ai reussi à reproduire, la méthode delete de la lib python n'est pas compatible à priori avec la version v1.8 d'influxdb :/

**Comment by m4dm4rtig4n** [comment]
Bon pas envie de passer du temps sur un debug sur une veille version d'influxdb, je met un commentaire comme quoi la feature fonctionne uniquement avec influxdb > 2.0
