### ISSUE TITLE
[BUG] - erreur de transfert des données vers l'interface web

### ISSUE THREAD

**Issue by grrosminet** [MyElectricalData/myelectricaldata#377]
**Description du bug**
A chaque couverture du dashboard, suite a la sélection du PDL, j'ai un message rapportant une erreur AJAX sur une table de données

Dans la console du navigateur je peux voir : 500 Internal Server Error

Dans les logs du plugin : 
```
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 594, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
2023-07-07 13:51:23.810 -    ERROR : Exception on /datatable/**************/consumption_detail [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/main.py", line 224, in datatable
    return Ajax(usage_point_id).datatable(measurement_direction, request.args)
  File "/app/models/ajax.py", line 481, in datatable
    all_data = app.DB.get_detail_datatable(
  File "/app/models/database.py", line 1022, in get_detail_datatable
    result = self.session.scalars(select(table)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1706, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 594, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: false
home_assistant:
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: mqtt.maison.lan
  password: 'null'
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: 'null'
myelectricaldata:
  *******************:
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2062'
    consumption_price_hc: '0.1615'
    consumption_price_hp: '0.2228'
    enable: 'true'
    name: maison
    offpeak_hours_0: 2h04-7h04;14h04-17h04
    offpeak_hours_1: 2h04-7h04;14h04-17h04
    offpeak_hours_2: 2h04-7h04;14h04-17h04
    offpeak_hours_3: 2h04-7h04;14h04-17h04
    offpeak_hours_4: 2h04-7h04;14h04-17h04
    offpeak_hours_5: 2h04-7h04;14h04-17h04
    offpeak_hours_6: 2h04-7h04;14h04-17h04
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: ***************************************************
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 0.8.16**

**Comment by m4dm4rtig4n** [comment]
Hello, je suis déjà sur le sujet, le soucis devrait disparaitre avec la 0.9.0 :)

**Comment by grrosminet** [comment]
👍Merci

**Comment by m4dm4rtig4n** [comment]
Arrivée de la 0.9.0 qui devrait fix le soucis d'ici quelques minutes.

**Comment by grrosminet** [comment]
Parfait
