### ISSUE TITLE
[BUG] - Internal Server Error après mise à jours des données

### ISSUE THREAD

**Issue by Dites33** [MyElectricalData/myelectricaldata#384]
**Description du bug**

Bonjour et merci pour la prise en charge de ce ticket, j'espère que je serais clair

Installation sur mini pc (VM proxmox), l'ensemble de HA va taper dans une base postgressql (autre VM)

Après installation de l'addon la mise à jour des données a commencé. 
J'ai mis dans la configuration une période depuis 01/01/2019 pour la consommation et depuis 01/01/2023 pour la production solaire (mais sur le site Enedis mes premières  production datent de Mars, contrat OA Enedis oblige).

Si pendant plusieurs heures hier la mise à jour a fonctionné (je pouvais accéder aux données du PDL via l'addon même si c'étant noté import en cours), ce matin cela ne fonctionne plus. J'ai le message "internal server error" après choix du PDL dans l'addon. Je mets le log ci dessous. J'y vois un 'keyerror" sur l'année 2022 à priori dans un consommation / production (en sachant que je n'ai produit que depuis le 08 mars 2023 sur le site Enedis).

Merci pour votre aide même en période de vacances ;)

<details>
<summary>Logs visible dans les journaux HA</summary>

```yaml
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /static/img/discord.png HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:04.743 -     INFO : 172.30.32.1:0 - "GET /img/enedis.png HTTP/1.1" 200
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /static/img/enedis.png HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:04.747 -     INFO : 172.30.32.1:0 - "GET /img/paypal.png HTTP/1.1" 200
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /static/img/paypal.png HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:04.757 -     INFO : 172.30.32.1:0 - "GET /img/loading.gif HTTP/1.1" 200
2023-08-01 09:18:04.759 -     INFO : 172.30.32.1:0 - "GET /img/icon.svg HTTP/1.1" 200
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /static/img/loading.gif HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /static/img/icon.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:04.797 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-01 09:18:04.797 -     INFO :  [NONE] CHECK DE L'ÉTAT DE LA PASSERELLE.
2023-08-01 09:18:04.797 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-01 09:18:04.943 -     INFO : status: True
2023-08-01 09:18:04.944 -     INFO : information: None
2023-08-01 09:18:04.944 -     INFO : nb_client: 2446
2023-08-01 09:18:04.944 -     INFO : waiting_estimation: 0.0s
2023-08-01 09:18:04.945 -     INFO : 172.30.32.1:0 - "GET /gateway_status/ HTTP/1.1" 200
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /gateway_status/ HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:04.954 -     INFO : 172.30.32.1:0 - "GET /img/success.png HTTP/1.1" 200
[01/Aug/2023:09:18:04 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /static/img/success.png HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:05.199 -     INFO : 127.0.0.1:42060 - "GET / HTTP/1.1" 200
[01/Aug/2023:09:18:05 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /import_status HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
[01/Aug/2023:09:18:09 +0200] 200 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /import_status HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:10.298 -     INFO : 127.0.0.1:42084 - "GET / HTTP/1.1" 200
2023-08-01 09:18:12.161 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-01 09:18:12.161 -     INFO :  REFRESH ORM OBJECTS
2023-08-01 09:18:12.161 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-01 09:18:12.860 -     INFO : 172.30.32.1:0 - "GET /usage_point_id/19944862497680 HTTP/1.1" 500
[01/Aug/2023:09:18:12 +0200] 500 fe80::6db7:21f:3e06:cd8c, 172.30.32.1(172.30.32.2) GET /usage_point_id/19944862497680 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188)
2023-08-01 09:18:12.860 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 28, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 335, in display
    self.consumption_vs_production(year)
  File "/app/templates/usage_point.py", line 723, in consumption_vs_production
    for month, value in self.recap_production_data[year]["month"].items():
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '2022'
2023-08-01 09:18:15.387 -     INFO : 127.0.0.1:59092 - "GET / HTTP/1.1" 200
2023-08-01 09:18:20.471 -     INFO : 127.0.0.1:59102 - "GET / HTTP/1.1" 200
2023-08-01 09:18:25.564 -     INFO : 127.0.0.1:36700 - "GET / HTTP/1.1" 200
2023-08-01 09:18:30.678 -     INFO : 127.0.0.1:36708 - "GET / HTTP/1.1" 200
2023-08-01 09:18:35.766 -     INFO : 127.0.0.1:59044 - "GET / HTTP/1.1" 200
2023-08-01 09:18:40.853 -     INFO : 127.0.0.1:59060 - "GET / HTTP/1.1" 200
2023-08-01 09:18:45.939 -     INFO : 127.0.0.1:49184 - "GET / HTTP/1.1" 200
2023-08-01 09:18:51.027 -     INFO : 127.0.0.1:49190 - "GET / HTTP/1.1" 200
2023-08-01 09:18:56.134 -     INFO : 127.0.0.1:33918 - "GET / HTTP/1.1" 200
2023-08-01 09:19:01.223 -     INFO : 127.0.0.1:33934 - "GET / HTTP/1.1" 200
2023-08-01 09:19:06.318 -     INFO : 127.0.0.1:51066 - "GET / HTTP/1.1" 200
2023-08-01 09:19:11.410 -     INFO : 127.0.0.1:51072 - "GET / HTTP/1.1" 200
2023-08-01 09:19:16.522 -     INFO : 127.0.0.1:40272 - "GET / HTTP/1.1" 200
```
</details>

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400  # 4H
debug: true
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
# Par défaut le backend en local dans le /data/cache.db du conteneur.
# Mais il est possible de basculer sur une base de données externe de type SQLite ou PostgreSQL
# Exemple pour Postgres :
# storage_uri: postgresql://myelectricaldata:myelectricaldata@postgres:5432/myelectricaldata
tempo:
  enable: false
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: false
  hostname: influxdb
  port: 8086
  token: myelectricaldata
  org: myelectricaldata
  bucket: myelectricaldata
  # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
  # mais va augmenter la consommation mémoire & CPU et donc à activer uniquement sur un hardware robuste.
  method: synchronous    # Mode disponible : synchronous / asynchronous / batching
  # batching_options permet uniquement de configurer la methode `batching`.
  # Pour plus d'information : https://github.com/influxdata/influxdb-client-python#batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: mosquitto
  port: 1883
  username: xxxxxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxxxxx
  prefix: myelectricaldata
  client_id: myelectricaldata     # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "xxxxxxxxxxxxxxxxxxxxx":
    enable: 'true'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    name: "Maison"
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.222'
    consumption_price_hc: '0.222'
    consumption_price_hp: '0.222'
    consumption_max_date: "2019-01-01"
    consumption_detail_max_date: "2019-01-01"
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_price: '0.10'
    production_max_date: "2023-01-01"
    production_detail_max_date: "2023-01-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'

```
</details>

**Type d'installation**

- [ ] Docker
- [x ] HassIO

**Version : 0.9.0**
**Home Assistant 2023.7.3**
**Supervisor 2023.07.1**
**Operating System 10.3**
**Interface utilisateur : 20230705.1 - latest**

**Comment by m4dm4rtig4n** [comment]
Peut tu refaire un test sur la 0.9.1 stp ?
