### ISSUE TITLE
[BUG] - Erreur python au lancement du conteneur

### ISSUE THREAD

**Issue by fbst999** [MyElectricalData/myelectricaldata#385]
**Description du bug**
Merci de me détailler au mieux le bug et une procédure pour le reproduire si possible.
```
NameError: name 'config' is not defined. Did you mean: 'Config'?
Traceback (most recent call last):
  File "/app/main.py", line 12, in <module>
    from init import CONFIG, DB
  File "/app/init.py", line 26, in <module>
    if "log2file" in config and config["log2file"]:
                     ^^^^^^
```
Le problème se présente lorsque je tente de déployer une image docker provenant de docker hub:
https://hub.docker.com/r/m4dm4rtig4n/myelectricaldata

j'ai essayé depuis deux hôtes docker, l'un étant un NAS QNAP et l'autre un serveur docker avec docker compose.
Les deux fournissent la même erreur.
Le docker-compose.yaml fourni sur ce repository a été utilisé sur l'hôte disposant de docker compose.

le fichier config.yaml n'est pas encore rempli car le conteneur ne se lance pas.

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version Docker: 24.0.5**
**Version Docker Compose: 2.20.2**

Merci d'avance pour votre aide

**Comment by fbst999** [comment]
en complément d'info, j'ai aussi reproduit le contenu du docker file sur un conteneur "vide" avec un ubuntu22.04 en exécutant les commandes qui sont effectuées lors du provisionnement du conteneur et j'ai malheureusement toujours la même erreur. 

Et j'ai tenté de renommer le config en Config ligne 26:
`if "log2file" in Config and Config["log2file"]:`

et cette fois ci l'erreur devient:
`Traceback (most recent call last):
  File "/opt/myelectricaldata/app/main.py", line 12, in <module>
    from init import CONFIG, DB
  File "/opt/myelectricaldata/app/init.py", line 26, in <module>
    if "log2file" in Config and Config["log2file"]:
TypeError: argument of type 'type' is not iterable`

**Comment by fbst999** [comment]
le problème a été résolu, il me manquait une étape consitant à mettre le contenu du fichier yaml dans le dossié mappé sur le conteneur.
