### ISSUE TITLE
[BUG] - l'addon MyElectricalData ne démarre plus - cannot import name MQTT

### ISSUE THREAD

**Issue by cosygarcia** [MyElectricalData/myelectricaldata#387]
**Description du bug**
L'addon ne démarre plus avec le message d'erreur : cannot import name 'MQTT' from 'init' (/app/init.py)

root@vm03:~# docker ps -a | grep myelec
3d6648e1ec90   ghcr.io/alexbelgium/myelectricaldata-aarch64:0.9.0          "/usr/bin/env /entry…"   5 seconds ago       Created                                                                                                          addon_db21ed7f_enedisgateway2mqtt

root@vm03:~# docker logs -f 3d6648e1ec90
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: MyElectricalData
 Use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.9.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / qemuarm-64)
 Home Assistant Core: 2023.8.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CONFIG_LOCATION='/config/myelectricaldata/config.yaml'
TZ='Europe/Paris'
mqtt_autodiscover='false'
verbose='true'
/etc/cont-init.d/01-custom_script.sh: executing
[17:34:02] INFO: Execute /config/addons_autoscripts/enedisgateway2mqtt.sh if existing
[17:34:02] INFO: ... no script found
/etc/cont-init.d/32-nginx_ingress.sh: executing
/etc/cont-init.d/91-mqtt_autodiscover.sh: executing
/etc/cont-init.d/99-run.sh: executing
creating symlink
[17:34:15] INFO: Using database file found in /config/myelectricaldata
[17:34:15] INFO: Using config file found in /config/myelectricaldata/config.yaml
Config file is a valid yaml

[17:34:15] INFO: Starting nginx

[17:34:15] INFO: Starting the app

2023-08-08 17:34:17.316 -     INFO : Display configuration :
2023-08-08 17:34:17.316 -     INFO :   cycle: 3600
2023-08-08 17:34:17.316 -     INFO :   debug: True
2023-08-08 17:34:17.316 -     INFO :   home_assistant:
2023-08-08 17:34:17.316 -     INFO :     discovery_prefix: homeassistant
2023-08-08 17:34:17.316 -     INFO :     enable: False
2023-08-08 17:34:17.316 -     INFO :     card_myenedis: True
2023-08-08 17:34:17.316 -     INFO :   influxdb:
2023-08-08 17:34:17.317 -     INFO :     bucket: myelectricaldata
2023-08-08 17:34:17.317 -     INFO :     enable: False
2023-08-08 17:34:17.317 -     INFO :     hostname: influxdb
2023-08-08 17:34:17.317 -     INFO :     method: synchronous
2023-08-08 17:34:17.317 -     INFO :     org: myelectricaldata
2023-08-08 17:34:17.317 -     INFO :     port: 8086
2023-08-08 17:34:17.317 -     INFO :     token: ** hidden **
2023-08-08 17:34:17.317 -     INFO :   log2file: False
2023-08-08 17:34:17.317 -     INFO :   mqtt:
2023-08-08 17:34:17.317 -     INFO :     client_id: myelectricaldata
2023-08-08 17:34:17.317 -     INFO :     enable: False
2023-08-08 17:34:17.317 -     INFO :     hostname: ''
2023-08-08 17:34:17.317 -     INFO :     password: ** hidden **
2023-08-08 17:34:17.317 -     INFO :     port: 1883
2023-08-08 17:34:17.318 -     INFO :     prefix: myelectricaldata
2023-08-08 17:34:17.318 -     INFO :     qos: 0
2023-08-08 17:34:17.318 -     INFO :     retain: True
2023-08-08 17:34:17.318 -     INFO :     username:
2023-08-08 17:34:17.318 -     INFO :   myelectricaldata:
2023-08-08 17:34:17.318 -     INFO :     XXXXXXXXXXXXXX:
2023-08-08 17:34:17.318 -     INFO :       activation_date_daily:
2023-08-08 17:34:17.318 -     INFO :       activation_date_detail:
2023-08-08 17:34:17.318 -     INFO :       cache: True
2023-08-08 17:34:17.318 -     INFO :       consumption: True
2023-08-08 17:34:17.318 -     INFO :       consumption_detail: True
2023-08-08 17:34:17.318 -     INFO :       consumption_detail_max_date: 2023-01-01
2023-08-08 17:34:17.318 -     INFO :       consumption_max_date: 2023-01-01
2023-08-08 17:34:17.318 -     INFO :       consumption_price_hc: 0.1615
2023-08-08 17:34:17.318 -     INFO :       consumption_price_hp: 0.2228
2023-08-08 17:34:17.318 -     INFO :       enable: True
2023-08-08 17:34:17.318 -     INFO :       name: Maison
2023-08-08 17:34:17.319 -     INFO :       offpeak_hours: 22H56-6H56
2023-08-08 17:34:17.319 -     INFO :       plan: HC/HP
2023-08-08 17:34:17.319 -     INFO :       refresh_addresse: False
2023-08-08 17:34:17.319 -     INFO :       refresh_contract: False
2023-08-08 17:34:17.319 -     INFO :       token: ** hidden **
2023-08-08 17:34:17.319 -     INFO :   tempo:
2023-08-08 17:34:17.319 -     INFO :     enable: False
2023-08-08 17:34:17.319 -     INFO :     price_blue_hc: 0.097
2023-08-08 17:34:17.319 -     INFO :     price_blue_hp: 0.1249
2023-08-08 17:34:17.319 -     INFO :     price_red_hc: 0.1216
2023-08-08 17:34:17.319 -     INFO :     price_red_hp: 0.6712
2023-08-08 17:34:17.319 -     INFO :     price_white_hc: 0.114
2023-08-08 17:34:17.319 -     INFO :     price_white_hp: 0.1508
2023-08-08 17:34:17.319 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-08 17:34:17.319 -     INFO : Check config.yaml :
2023-08-08 17:34:17.319 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-08 17:34:17.320 -     INFO :   CONFIG VALID
2023-08-08 17:34:17.320 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2023-08-08 17:34:18.497 -     INFO : Configure Databases
2023-08-08 17:34:18.554 -     INFO :  => day
2023-08-08 17:34:18.560 -     INFO :  => call_number
2023-08-08 17:34:18.564 -     INFO :  => max_call
2023-08-08 17:34:18.569 -     INFO :  => version
2023-08-08 17:34:18.574 -     INFO :  => lock
2023-08-08 17:34:18.578 -     INFO :  => lastUpdate
2023-08-08 17:34:18.579 -     INFO :  Success
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from routers import account
  File "/app/routers/account.py", line 3, in <module>
    from models.ajax import Ajax
  File "/app/models/ajax.py", line 8, in <module>
    from models.jobs import Job
  File "/app/models/jobs.py", line 7, in <module>
    from models.export_home_assistant import HomeAssistant
  File "/app/models/export_home_assistant.py", line 9, in <module>
    from init import MQTT, DB, CONFIG
ImportError: cannot import name 'MQTT' from 'init' (/app/init.py)
[17:34:19] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Type d'installation**
Debian 11 + Docker

**Versions :
Add-on version: 0.9.0
Home Assistant Core: 2023.8.1
Home Assistant Supervisor: 2023.07.1
Je n'ai pas de broker MQTT installé

**Comment by IPv777** [comment]
same issue here !

**Comment by FlorianLaunay** [comment]
Same issue for me

**Comment by BenjaminD3E** [comment]
Same issue for me, first install

**Comment by cosygarcia** [comment]
Comment installer ce fork en attendant le merge ?
J'utilise un HA supervised sous Debian 11.

**Comment by m4dm4rtig4n** [comment]
Fix dans la 0.9.1 qui va pop prochainement.
Désolé j'était en vacances pendant 15j et complétement déconnecter :)

**Comment by cosygarcia** [comment]
une idée de la date ? D'avance un grand merci pour votre travail.

**Comment by m4dm4rtig4n** [comment]
La 0.9.1 est release.
Avez-vous encore le bug ?

**Comment by cosygarcia** [comment]
L'addon démarre correctement en 0.9.1.
Encore merci.

Le mer. 23 août 2023 à 13:28, m4dm4rtig4n ***@***.***> a
écrit :

**Comment by BenjaminD3E** [comment]
Idem, avec la version 0.9.1 tout fonctionne ! Merci beaucoup pour la réactivité et la qualité des développements !
