### ISSUE TITLE
[BUG] - probleme d'import de données

### ISSUE THREAD

**Issue by dudu7731** [MyElectricalData/myelectricaldata#389]
**Description du bug**
J'ai un problème d'import de données depuis 2 jours
![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/443d101f-750a-45d9-b690-c778fe536fe0)
![image](https://github.com/MyElectricalData/myelectricaldata/assets/117290248/98e16805-bbbf-42b3-96ee-93a45233bab0)

voici des extraits de log : 
```
2023-08-10 08:33:38.080 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:33:38.080 -     INFO :  [NONE] CHECK DE L'ÉTAT DE LA PASSERELLE.
2023-08-10 08:33:38.080 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:33:38.883 -     INFO : 10.0.0.101:56536 - "GET /gateway_status/ HTTP/1.0" 500
2023-08-10 08:33:38.884 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 154, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError
```

```
2023-08-10 08:31:45.776 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:31:45.776 -     INFO :   CHARGEMENT DES DONNÉES DEPUIS MYELECTRICALDATA 2022-01-01 => 2023-08-12
2023-08-10 08:31:45.777 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:31:45.917 -    ERROR : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 109, in run
    "description": json.loads(data.text)["detail"],
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-10 08:31:45.917 -    ERROR : Expecting value: line 1 column 1 (char 0)
2023-08-10 08:31:45.917 -    ERROR : ['Echec de la récupération des données.', ' => MyElectricalData est indisponible.', ' => 2022-01-01 -> 2023-08-12']
```

```
2023-08-10 08:31:44.341 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:31:44.341 -     INFO :  RÉCUPÉRATION DES DONNÉES TEMPO :
2023-08-10 08:31:44.341 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/models/jobs.py", line 61, in job_import_data
    self.get_tempo()
  File "/app/models/jobs.py", line 373, in get_tempo
    return Tempo().fetch()
           ^^^^^^^^^^^^^^^
  File "/app/models/query_tempo.py", line 66, in fetch
    result = self.run()
             ^^^^^^^^^^
  File "/app/models/query_tempo.py", line 45, in run
    "description": json.loads(query_response.text)["detail"]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-10 08:31:44.614 -    ERROR : ['Erreur lors de la récupération des données tempo', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
2023-08-10 08:31:44.617 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:31:44.617 -     INFO :  RÉCUPÉRATION DES DONNÉES ECOWATT :
2023-08-10 08:31:44.617 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "/app/models/jobs.py", line 72, in job_import_data
    self.get_ecowatt()
  File "/app/models/jobs.py", line 378, in get_ecowatt
    return Ecowatt().fetch()
           ^^^^^^^^^^^^^^^^^
  File "/app/models/query_ecowatt.py", line 71, in fetch
    result = self.run()
             ^^^^^^^^^^
  File "/app/models/query_ecowatt.py", line 46, in run
    "description": json.loads(query_response.text)["detail"]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-10 08:31:44.880 -    ERROR : ['Erreur lors de la récupération des données EcoWatt', JSONDecodeError('Expecting value: line 1 column 1 (char 0)')]
```

```
2023-08-10 08:31:01.876 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:31:01.877 -     INFO :   CHARGEMENT DES DONNÉES DEPUIS MYELECTRICALDATA 2023-08-07 => 2023-08-11
2023-08-10 08:31:01.877 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-08-10 08:31:02.051 -    ERROR : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 109, in run
    "description": json.loads(data.text)["detail"],
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-10 08:31:02.063 -    ERROR : Expecting value: line 1 column 1 (char 0)
2023-08-10 08:31:02.066 -     INFO : 10.0.0.101:45794 - "GET /usage_point_id/23170622228978/consumption/import/2023-08-09 HTTP/1.0" 500
2023-08-10 08:31:02.075 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/action.py", line 63, in fetch_data
    return Ajax(usage_point_id).fetch(target, date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/models/ajax.py", line 221, in fetch
    ).fetch(date)
      ^^^^^^^^^^^
  File "/app/models/query_daily.py", line 183, in fetch
    if "error" in result and result["error"]:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

```

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: MyElectricalData
  enable: true
  hostname: xxxxxxxxxxxxxxxxxxx
  method: synchronous
  org: production
  port: 8086
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: xxxxxxxxxxxxx
  password: xxxxxxxxxxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: admin
myelectricaldata:
  'xxxxxxxxxxxxx':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.2276'
    consumption_price_hc: '0.1828'
    consumption_price_hp: '0.246'
    enable: 'true'
    name: Home Enedis
    offpeak_hours_0: 22h00-06h00
    offpeak_hours_1: 22h00-06h00
    offpeak_hours_2: 22h00-06h00
    offpeak_hours_3: 22h00-06h00
    offpeak_hours_4: 22h00-06h00
    offpeak_hours_5: 22h00-06h00
    offpeak_hours_6: 22h00-06h00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'false'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
tempo:
  enable: true
  price_blue_hc: 0.1056
  price_blue_hp: 0.1369
  price_red_hc: 0.1328
  price_red_hp: 0.7324
  price_white_hc: 0.1246
  price_white_hp: 0.1654
wipe_influxdb: false

```
</details>

**Type d'installation**

- [ ] Docker
- [x ] HassIO

**Version : 0.9.0**

**Comment by dudu7731** [comment]
serveur revenu
