### ISSUE TITLE
[BUG] - Exception export Tempo d'un PDL production only

### ISSUE THREAD

**Issue by ioull** [MyElectricalData/myelectricaldata#399]
**Description du bug**
Lors de l'esport des données TEMPO vers MQTT j'ai l'exception suivante :
```
2023-08-23 11:24:38.045 -     INFO : Envoie des données Tempo
Traceback (most recent call last):
  File "/app/models/jobs.py", line 514, in export_mqtt
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 477, in run
    export_mqtt.tempo()
  File "/app/models/export_mqtt.py", line 452, in tempo
    mqtt_data[f"{self.usage_point_id}/consumption/annual/{year}/thisYear/tempo/{color}/Wh"] = round(tempo['Wh'], 2)
                                                                                                    ~~~~~^^^^^^
TypeError: 'float' object is not subscriptable
2023-08-23 11:24:38.051 -    ERROR : Erreur lors de la export mqtt
2023-08-23 11:24:38.052 -    ERROR : 'float' object is not subscriptable
```
Il s'agit d'un PDL sans consomation avec seulement de la production.

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: eg2mqtt
  enable: false
  hostname: influxdb
  method: synchronous
  org: ioull
  port: 8086
  token: TOKENTOKENTOKEN
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: mosquitto
  password: PASSWD
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: enedisgw
myelectricaldata:
  'XXXXXXXXXXXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'false'
    consumption_detail: 'false'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'false'
    consumption_price_base: '1'
    consumption_price_hc: '2'
    consumption_price_hp: '3'
    enable: 'true'
    name: Production
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'true'
    production_detail: 'true'
    production_detail_max_date: '2022-08-18'
    production_max_date: '2022-08-18'
    production_max_power: 'false'
    production_price: '0.60275'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: TOKENTOKENTOKEN=
tempo:
  enable: true
  price_blue_hc: 0.1056
  price_blue_hp: 0.1369
  price_red_hc: 0.1328
  price_red_hp: 0.7324
  price_white_hc: 0.1246
  price_white_hp: 0.1654
wipe_influxdb: false
```
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : X.X.X**

**Comment by m4dm4rtig4n** [comment]
Je n'arrive pas à reproduire le bug pour l'instant :/

**Comment by m4dm4rtig4n** [comment]
Fix dans la 0.9.2 (0.9.2.b2)
